In [ ]:
import torch
from PolyTensor import PolyTensor

X = PolyTensor([0., 1.], degree=5)
w_init = torch.tensor([1., -1., 2.])
w = PolyTensor(w_init + X, requires_grad=True)

opt = torch.optim.SGD([w], lr=0.1, foreach=False)

for _ in range(3):
    opt.zero_grad()
    loss = (w ** 3).sum()
    loss.backward()
    opt.step()

In [ ]:
X = PolyTensor([0., 1.], degree=3)
w_init = torch.tensor([1., -1., 2.])
w = PolyTensor(w_init + X, requires_grad=True)
loss = (w**3).sum()
loss.backward()

print("w.grad:")
for coeff in w.grad.coeffs:
    print(coeff)

# w1^3 + w2^3 + w3^3
# (3 w1^2, 3 w2^2, 3 w3^2)
# (w1, w2, w3) = (x+1, x-1, x+2)
# w.grad = (3 + 6 x + 3 x^2, 3 - 6 x + 3 x^2, 12 + 12 x + 3 x^2)
#        = (3, 3, 12) + (6, -6, 12) x + (3, 3, 3) x^2

w.grad:
tensor([ 3.,  3., 12.])
tensor([ 6., -6., 12.])
tensor([3., 3., 3.])
tensor([0., 0., 0.])
