In [16]:
import torch
from PolyTensor import PolyTensor

X = PolyTensor([0., 1.], degree=5)
w_init = torch.tensor([1., -1., 2.])
w = PolyTensor(w_init + X, requires_grad=True)

opt = torch.optim.SGD([w], lr=0.1, foreach=False)

for _ in range(3):
    opt.zero_grad()
    loss = (w ** 3).sum()
    loss.backward()
    opt.step()

print("w:")
for coeff in w.coeffs:
    print(coeff)

print("="*20)

print("w.grad:")
for coeff in w.grad.coeffs:
    print(coeff)

w:
tensor([ 0.4613, -2.7866,  0.4971])
tensor([ 0.1550,  5.9358, -0.0661])
tensor([-0.1645, -5.1470, -0.1100])
tensor([ 0.0790,  2.8251, -0.0334])
tensor([-0.0428, -1.0570, -0.0279])
tensor([ 0.0133,  0.2711, -0.0053])
w.grad:
tensor([0.9174, 9.7957, 1.1090])
tensor([  0.7698, -30.8780,  -0.3794])
tensor([-0.5751, 38.4496, -0.5804])
tensor([ -0.0701, -25.3711,  -0.0265])
tensor([1.5849e-01, 1.0300e+01, 8.6400e-03])
tensor([-0.1335, -2.7112,  0.0531])


In [25]:
X = PolyTensor([0., 1.], degree=3)
w_init = torch.tensor([1., -1., 2.])
w = PolyTensor(w_init + X, requires_grad=True)
loss = (w**3).sum()
loss.backward()

print("w.grad:")
for coeff in w.grad.coeffs:
    print(coeff)

# w1^3 + w2^3 + w3^3
# (3 w1^2, 3 w2^2, 3 w3^2)
# (w1, w2, w3) = (x+1, x-1, x+2)
# w.grad = (3 + 6 x + 3 x^2, 3 - 6 x + 3 x^2, 12 + 12 x + 3 x^2)

w.grad:
tensor([ 3.,  3., 12.])
tensor([ 6., -6., 12.])
tensor([3., 3., 3.])
tensor([0., 0., 0.])
