In [12]:
import torch
from PolyTensor import PolyTensor

X = PolyTensor([0., 1.], degree=5)
w_init = torch.tensor([1., -1., 2.])
w = PolyTensor(w_init + X, requires_grad=True)

opt = torch.optim.SGD([w], lr=0.1, foreach=False)

for _ in range(3):
    opt.zero_grad()
    loss = (w ** 3).sum()
    loss.backward()
    opt.step()

for coeff in w.coeffs:
    print(coeff)

tensor([ 0.4613, -2.7866,  0.4971])
tensor([ 0.1550,  5.9358, -0.0661])
tensor([-0.1645, -5.1470, -0.1100])
tensor([ 0.0790,  2.8251, -0.0334])
tensor([-0.0428, -1.0570, -0.0279])
tensor([ 0.0133,  0.2711, -0.0053])


In [ ]:
X = PolyTensor([0., 1.], degree=3)
w_init = torch.tensor([1., -1., 2.])
w = PolyTensor(w_init + X, requires_grad=True)
loss = (w**2).sum()
loss.backward()


In [3]:
# w1^2 + w2^2 + w3^2
# (2 w1, 2 w2, 2 w3)
# (w1, w2, w3) = (x+1, x-1, x+2)
# w.grad = (2 + 2x, -2 + 2x, 4 + 2x)

In [3]:
w.grad

PolyTensor((tensor([ 2., -2.,  4.]), tensor([2., 2., 2.]), tensor([0., 0., 0.]), tensor([0., 0., 0.])), requires_grad=False)

In [12]:
xt = torch.tensor([0.,1.], requires_grad=True)
print(xt.grad)

None
